module.exports = {
	plugins: [
		require('@ianvs/prettier-plugin-sort-imports'),
		require('prettier-plugin-tailwindcss'),
	],
	trailingComma: 'es5',
	tabWidth: 2,
	semi: false,
	singleQuote: true,
	useTabs: true,
	jsxSingleQuote: true,
	importOrder: [
		'react/*',
		'next/*',
		'clsx',
		'@/components/*',
		'@/utils/*',
		'@/hooks/*',
		'@/styles/*',
		'^[./]',
	],
	importOrderBuiltinModulesToTop: true,
	importOrderCaseInsensitive: true,
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
}
